services:

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=xxxx
      - PGID=xxxx
      - TZ=Europe/Athens
      - UMASK=022
      - VERSION=latest
    volumes:
      - /volume2/docker/plex:/config
      - /volume1/data/media:/data/media
    security_opt:
      - no-new-privileges:true
    # labels:
    # - "diun.enable=true"
    restart: unless-stopped
  