services:

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    network_mode: mydockerbridge
    environment:
      - PUID=xxxx
      - PGID=xxxx
      - TZ=Europe/Athens
      - UMASK=022
    volumes:
      - /volume2/docker/sabnzbd:/config
      - /volume1/data/usenet:/data/usenet
    ports:
      - 8080:8080
    security_opt:
      - no-new-privileges:true
    # labels:
    # - "diun.enable=true"
    restart: always