services:
  
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    network_mode: mydockerbridge
    environment:
      TZ: Europe/Athens
      UID: xxxx
      GID: xxxx
    ports:
      - 8096:8096
      - 8920:8920
    volumes:
      - /volume2/docker/emby:/config:rw
      - /volume1/data/media:/data/media
    # labels:
    #   - "diun.enable=true"
    restart: unless-stopped