services:
  
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    network_mode: mydockerbridge
    environment:
      PUID: xxxx
      PGID: xxxx
    ports:
      - 3010:3000
    volumes:
      - /volume2/docker/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    # labels:
    # - "diun.enable=true"
    restart: unless-stopped