services:
  
  diun:
    image: crazymax/diun:latest
    container_name: diun
    network_mode: mydockerbridge
    command: serve
    volumes:
      - /volume2/docker/diun:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Athens
      # - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 15 * * 0
      # - DIUN_WATCH_JITTER=30s
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true
      - DIUN_WATCH_RUNONSTARTUP=false
      - DIUN_NOTIF_GOTIFY_ENDPOINT=xxxxxxxxxx
      - DIUN_NOTIF_GOTIFY_TOKEN=xxxxxxxxxx
    # labels:
    # - "diun.enable=true"
    restart: unless-stopped