services:
  
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    network_mode: host
    cap_add:
      - CAP_NET_RAW
      - CAP_NET_BIND_SERVICE
      - CAP_CHOWN
    environment:
      - PIHOLE_UID=xxxx #CHANGE_TO_YOUR_UID
      - PIHOLE_GID=xxxx #CHANGE_TO_YOUR_GID
      - WEB_UID=xxxx #CHANGE_TO_YOUR_UID
      - WEB_GID=xxxx #CHANGE_TO_YOUR_GID
      - TZ=Europe/Athens #CHANGE_TO_YOUR_TZ
      - WEBPASSWORD=xxxxxxxxxx
      - DNSMASQ_LISTENING=local
      - WEB_PORT=8000
      - DNSMASQ_USER=pihole
      - FTLCONF_LOCAL_IPV4=192.168.178.200
    volumes:
      - /volume2/docker/pihole/dnsmasq.d:/etc/dnsmasq.d
      - /volume2/docker/pihole/pihole:/etc/pihole
    # labels:
    # - "diun.enable=true"
    restart: unless-stopped