services:
  
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    network_mode: container:gluetun # run on the vpn container's network
    environment:
      - PUID=xxxx
      - PGID=xxxx
      - TZ=Europe/Athens
      - UMASK=022
    volumes:
      - /volume2/docker/jackett:/config
      - /volume1/data:/downloads
    security_opt:
      - no-new-privileges:true
    # labels:
    # - "diun.enable=true"
    restart: always
  