services:

  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-omnibus
    container_name: scrutiny
    network_mode: mydockerbridge
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    ports:
      - 6091:8080/tcp # webapp
      - 8086:8086/tcp # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - /volume2/docker/scrutiny:/opt/scrutiny/config
      - /volume2/docker/scrutiny/influxdb:/opt/scrutiny/influxdb
    devices:
      - /dev/nvme0n1:/dev/nvme0n1
      - /dev/nvme1n1:/dev/nvme1n1
      - /dev/sata1:/dev/sata1
      - /dev/sata2:/dev/sata2
      - /dev/sata3:/dev/sata3
      - /dev/sata4:/dev/sata4
    environment:
      - SCRUTINY_WEB_INFLUXDB_TOKEN=xxxxxxxxxx
      - SCRUTINY_WEB_INFLUXDB_INIT_USERNAME=xxxxxxxxxx
      - SCRUTINY_WEB_INFLUXDB_INIT_PASSWORD=xxxxxxxxxx
      - COLLECTOR_CRON_SCHEDULE=0 */4 * * *
    security_opt:
      - no-new-privileges:true
    # labels:
    # - "diun.enable=true"
    restart: unless-stopped