services:

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    network_mode: mydockerbridge
    ports:
      - 8892:8080
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - DOZZLE_USERNAME=xxxxxxxxxx
      - DOZZLE_PASSWORD=xxxxxxxxxx
    # labels:
    # - "diun.enable=true"
    restart: always