services:
  
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    network_mode: mydockerbridge
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8112:8112 # deluge
      - 9696:9696 # prowlarr
      - 8191:8191 # flaresolverr
      - 9117:9117 # jackett
      - 8090:8090 # qbittorrent
      - 5076:5076 # nzbhydra2
      - 3333:3333 # bitmagnet
    volumes:
      - /volume2/docker/gluetun:/gluetun
    environment:
      - PUID=xxxx
      - PGID=xxxx
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=xxxxxxxxxx
      - WIREGUARD_PRESHARED_KEY=xxxxxxxxxx
      - WIREGUARD_ADDRESSES=10.134.182.231/32
      - SERVER_COUNTRIES=Netherlands
      - TZ=Europe/Athens
      - HTTPPROXY=off #change to on if you wish to enable
      - SHADOWSOCKS=off #change to on if you wish to enable
      - FIREWALL_OUTBOUND_SUBNETS=172.20.0.0/16,192.168.178.0/24 #change this in line with your subnet see note on guide.
      # - FIREWALL_VPN_INPUT_PORTS=12345 #uncomment this line and change the port as per the note on the guide
      - UPDATER_PERIOD=24h
    security_opt:
      - no-new-privileges:true
    # extra_hosts:
    #   - "bitmagnet-postgres: 172.20.0.121"
    # labels:
    #   - diun.enable=true
    restart: always